/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Lenovo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtn_productos = new javax.swing.JButton();
        jbtn_proveedores = new javax.swing.JButton();
        jbtn_clientes = new javax.swing.JButton();
        jbtn_restarar = new javax.swing.JButton();
        jbtn_punto_venta = new javax.swing.JButton();
        jbtn_ajustes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jm_Menu = new javax.swing.JMenuItem();
        jm_Cerrar_sesion = new javax.swing.JMenuItem();
        jm_Iniciar_sesion = new javax.swing.JMenuItem();
        jm_registra_usuario = new javax.swing.JMenuItem();
        jm_restauracion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jm_acerca_de = new javax.swing.JMenuItem();
        jm_ayuda_producto = new javax.swing.JMenu();
        jm_ayuda_productos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jbtn_productos.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icono_producto_1.png"))); // NOI18N
        jbtn_productos.setBorder(null);
        jbtn_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_productosActionPerformed(evt);
            }
        });

        jbtn_proveedores.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/Proveedores.png"))); // NOI18N
        jbtn_proveedores.setBorder(null);

        jbtn_clientes.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icono_cliente.png"))); // NOI18N
        jbtn_clientes.setBorder(null);

        jbtn_restarar.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_restarar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/recycle_empty_64.png"))); // NOI18N
        jbtn_restarar.setBorder(null);
        jbtn_restarar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_restararActionPerformed(evt);
            }
        });

        jbtn_punto_venta.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_punto_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/icono_venta.png"))); // NOI18N
        jbtn_punto_venta.setBorder(null);
        jbtn_punto_venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_punto_ventaActionPerformed(evt);
            }
        });

        jbtn_ajustes.setBackground(new java.awt.Color(255, 204, 204));
        jbtn_ajustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imges/MenuSalir.png"))); // NOI18N
        jbtn_ajustes.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_punto_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jbtn_restarar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_ajustes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtn_proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_productos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_punto_venta, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(jbtn_restarar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_ajustes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(103, 103, 103))
        );

        jMenu1.setText("Opciones ");

        jm_Menu.setText("Menu");
        jMenu1.add(jm_Menu);

        jm_Cerrar_sesion.setText("Cerrar sesión ");
        jMenu1.add(jm_Cerrar_sesion);

        jm_Iniciar_sesion.setText("Iniciar sesion ");
        jMenu1.add(jm_Iniciar_sesion);

        jm_registra_usuario.setText("Registrar usuario");
        jMenu1.add(jm_registra_usuario);

        jm_restauracion.setText("Restauración ");
        jMenu1.add(jm_restauracion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Información ");

        jm_acerca_de.setText("Acerca de..");
        jMenu2.add(jm_acerca_de);

        jMenuBar1.add(jMenu2);

        jm_ayuda_producto.setText("Ayuda");

        jm_ayuda_productos.setText("Productos");
        jm_ayuda_producto.add(jm_ayuda_productos);

        jMenuBar1.add(jm_ayuda_producto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_productosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_productosActionPerformed

    private void jbtn_punto_ventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_punto_ventaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_punto_ventaActionPerformed

    private void jbtn_restararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_restararActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_restararActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtn_ajustes;
    public javax.swing.JButton jbtn_clientes;
    public javax.swing.JButton jbtn_productos;
    public javax.swing.JButton jbtn_proveedores;
    public javax.swing.JButton jbtn_punto_venta;
    public javax.swing.JButton jbtn_restarar;
    public javax.swing.JMenuItem jm_Cerrar_sesion;
    public javax.swing.JMenuItem jm_Iniciar_sesion;
    public javax.swing.JMenuItem jm_Menu;
    public javax.swing.JMenuItem jm_acerca_de;
    private javax.swing.JMenu jm_ayuda_producto;
    public javax.swing.JMenuItem jm_ayuda_productos;
    public javax.swing.JMenuItem jm_registra_usuario;
    public javax.swing.JMenuItem jm_restauracion;
    // End of variables declaration//GEN-END:variables
}
